# Generated by Django 4.2.7 on 2025-12-18 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fine amount for overdue returns', max_digits=6)),
                ('fine_paid', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-borrowed_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='loans_user_id_efac20_idx'), models.Index(fields=['book', 'status'], name='loans_book_id_6360b6_idx'), models.Index(fields=['due_date'], name='loans_due_dat_3e4b70_idx')],
            },
        ),
    ]
